# -*- coding: utf-8 -*-
"""Untitled67.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgZlYBJtvz04T__2c7BHn094XSokM9Mf
"""

# ============================================================
# FINAL IMPROVED rPPG CODE
# Green + POS + CHROM + Improved Decision Logic
# Goal: reduce HR error across fixed and moving videos
# ============================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, find_peaks, detrend, medfilt
from google.colab.patches import cv2_imshow
from google.colab import files

# =========================
# CONFIG
# =========================

MIN_BPM = 40
MAX_BPM = 140

# Optional فقط برای بررسی خطا؛ اگر نمی‌خوای نمایش داده بشه None بگذار
GROUND_TRUTH_HR = None

# =========================
# Upload video
# =========================

uploaded = files.upload()
VIDEO_PATH = list(uploaded.keys())[0]
print("Uploaded video:", VIDEO_PATH)

# =========================
# Helper functions
# =========================

def normalize_signal(x):
    x = np.asarray(x, dtype=float)
    return (x - np.nanmean(x)) / (np.nanstd(x) + 1e-8)


def remove_spikes(x, kernel_size=7, z_thresh=3.5):
    x = np.asarray(x, dtype=float)

    if len(x) < kernel_size:
        return x

    y = x.copy()
    med = medfilt(y, kernel_size=kernel_size)

    diff = y - med
    mad = np.median(np.abs(diff)) + 1e-8
    z = 0.6745 * diff / mad

    y[np.abs(z) > z_thresh] = med[np.abs(z) > z_thresh]

    return y


def bandpass_filter(x, fs, min_bpm=40, max_bpm=140, order=4):
    x = np.asarray(x, dtype=float)

    low = min_bpm / 60.0
    high = max_bpm / 60.0

    try:
        b, a = butter(order, [low, high], btype="bandpass", fs=fs)

        if len(x) <= 3 * max(len(a), len(b)):
            return x

        return filtfilt(b, a, x)

    except Exception as e:
        print("Filter warning:", e)
        return x


def estimate_hr_fft(signal, fs):
    signal = np.asarray(signal, dtype=float)

    if len(signal) < int(fs * 6):
        return None, 0.0

    x = signal - np.mean(signal)
    x = x * np.hanning(len(x))

    freqs = np.fft.rfftfreq(len(x), d=1.0 / fs)
    spec = np.abs(np.fft.rfft(x))

    bpm = freqs * 60.0
    mask = (bpm >= MIN_BPM) & (bpm <= MAX_BPM)

    if not np.any(mask):
        return None, 0.0

    bpm_valid = bpm[mask]
    spec_valid = spec[mask]

    idx = np.argmax(spec_valid)
    hr = float(bpm_valid[idx])

    peak_power = spec_valid[idx]
    median_power = np.median(spec_valid) + 1e-8
    confidence = float(peak_power / median_power)

    return hr, confidence


def estimate_hr_peak(signal, fs):
    signal = np.asarray(signal, dtype=float)

    if len(signal) < int(fs * 6):
        return None, 0.0

    x = signal - np.mean(signal)

    min_distance = max(1, int(fs * 60.0 / MAX_BPM))
    prominence = max(0.28 * np.std(x), 0.08)

    peaks, _ = find_peaks(
        x,
        distance=min_distance,
        prominence=prominence
    )

    if len(peaks) < 3:
        return None, 0.0

    intervals = np.diff(peaks) / fs
    bpms = 60.0 / intervals

    bpms = bpms[
        (bpms >= MIN_BPM) &
        (bpms <= MAX_BPM)
    ]

    if len(bpms) < 2:
        return None, 0.0

    hr = float(np.median(bpms))

    variability = np.std(bpms)
    confidence = float(1.0 / (1.0 + variability / 8.0))

    return hr, confidence


def weighted_median(values, weights):
    values = np.asarray(values, dtype=float)
    weights = np.asarray(weights, dtype=float)

    order = np.argsort(values)
    values = values[order]
    weights = weights[order]

    cumulative = np.cumsum(weights)
    cutoff = np.sum(weights) / 2.0

    return float(values[np.searchsorted(cumulative, cutoff)])


# =========================
# ROI functions
# =========================

def keep_roi_inside_frame(roi, frame_shape):
    x, y, w, h = roi
    H, W = frame_shape[:2]

    x = max(0, x)
    y = max(0, y)
    w = max(1, min(w, W - x))
    h = max(1, min(h, H - y))

    return x, y, w, h


def get_rois(face, frame_shape):
    x, y, w, h = face

    rois = {
        "forehead": (
            x + int(0.30 * w),
            y + int(0.08 * h),
            int(0.40 * w),
            int(0.18 * h)
        ),
        "left_cheek": (
            x + int(0.18 * w),
            y + int(0.52 * h),
            int(0.22 * w),
            int(0.18 * h)
        ),
        "right_cheek": (
            x + int(0.60 * w),
            y + int(0.52 * h),
            int(0.22 * w),
            int(0.18 * h)
        )
    }

    return {
        name: keep_roi_inside_frame(roi, frame_shape)
        for name, roi in rois.items()
    }


def mean_rgb_from_roi(frame, roi):
    x, y, w, h = roi
    patch = frame[y:y+h, x:x+w]

    if patch.size == 0:
        return None

    mean_bgr = np.mean(patch.reshape(-1, 3), axis=0)
    mean_rgb = mean_bgr[::-1]

    return mean_rgb


# =========================
# POS and CHROM
# =========================

def pos_rppg(rgb_signal, fs, window_seconds=1.6):
    rgb_signal = np.asarray(rgb_signal, dtype=float)
    n = len(rgb_signal)
    L = int(window_seconds * fs)

    h = np.zeros(n)

    if n < L:
        return h

    for start in range(0, n - L + 1):
        end = start + L

        C = rgb_signal[start:end].T
        mean_color = np.mean(C, axis=1, keepdims=True)
        Cn = C / (mean_color + 1e-8)

        S1 = Cn[1] - Cn[2]
        S2 = Cn[1] + Cn[2] - 2 * Cn[0]

        alpha = np.std(S1) / (np.std(S2) + 1e-8)

        H = S1 + alpha * S2
        H = H - np.mean(H)

        h[start:end] += H

    return h


def chrom_rppg(rgb_signal, fs, window_seconds=1.6):
    rgb_signal = np.asarray(rgb_signal, dtype=float)
    n = len(rgb_signal)
    L = int(window_seconds * fs)

    h = np.zeros(n)

    if n < L:
        return h

    for start in range(0, n - L + 1):
        end = start + L

        C = rgb_signal[start:end].T
        mean_color = np.mean(C, axis=1, keepdims=True)
        Cn = C / (mean_color + 1e-8)

        R = Cn[0]
        G = Cn[1]
        B = Cn[2]

        X = 3 * R - 2 * G
        Y = 1.5 * R + G - 1.5 * B

        alpha = np.std(X) / (np.std(Y) + 1e-8)

        H = X - alpha * Y
        H = H - np.mean(H)

        h[start:end] += H

    return h


# =========================
# Improved Smart final selector
# =========================

def smart_select_hr(results):
    green_fft = results["green"]["fft_hr"]
    green_peak = results["green"]["peak_hr"]

    pos_fft = results["pos"]["fft_hr"]
    pos_peak = results["pos"]["peak_hr"]

    chrom_fft = results["chrom"]["fft_hr"]
    chrom_peak = results["chrom"]["peak_hr"]

    candidates = []

    for method in results:
        for key in ["fft", "peak"]:
            hr = results[method][f"{key}_hr"]
            conf = results[method][f"{key}_conf"]

            if hr is not None and MIN_BPM <= hr <= MAX_BPM:
                candidates.append((f"{method}_{key}", hr, conf))

    if len(candidates) == 0:
        return None, "failed"

    # ========================================================
    # Rule A: اگر Green FFT و Green Peak خیلی نزدیک‌اند
    # معمولاً برای ویدیوهای ثابت یا حرکت کم بهترین انتخاب است
    # ========================================================

    if green_fft is not None and green_peak is not None:
        if 50 <= green_fft <= 120 and 50 <= green_peak <= 120:
            if abs(green_fft - green_peak) <= 5:
                return (green_fft + green_peak) / 2.0, "green_fft_peak_agree"

    # ========================================================
    # Rule B: اگر CHROM FFT و CHROM Peak نزدیک‌اند
    # برای بعضی ویدیوهای متحرک بهتر جواب داده
    # ========================================================

    if chrom_fft is not None and chrom_peak is not None:
        if 50 <= chrom_fft <= 120 and 50 <= chrom_peak <= 120:
            if abs(chrom_fft - chrom_peak) <= 7:
                return (chrom_fft + chrom_peak) / 2.0, "chrom_fft_peak_agree"

    # ========================================================
    # Rule C: اگر POS FFT و POS Peak نزدیک‌اند
    # ========================================================

    if pos_fft is not None and pos_peak is not None:
        if 50 <= pos_fft <= 120 and 50 <= pos_peak <= 120:
            if abs(pos_fft - pos_peak) <= 7:
                return (pos_fft + pos_peak) / 2.0, "pos_fft_peak_agree"

    # ========================================================
    # Rule D: مشکل اصلی دیتاست تو:
    # FFT روی 42 تا 58 گیر می‌کند، ولی peakهای POS/CHROM نزدیک HR واقعی‌اند.
    # پس اگر حداقل دو FFT پایین داریم و peak بین 65 تا 95 داریم،
    # FFT پایین reject می‌شود.
    # ========================================================

    fft_values = [green_fft, pos_fft, chrom_fft]
    low_fft_count = sum(
        1 for x in fft_values
        if x is not None and 40 <= x < 60
    )

    rescue_peaks = []

    for name, hr, conf in candidates:
        if "peak" in name and 65 <= hr <= 95:
            rescue_peaks.append((name, hr, conf))

    if low_fft_count >= 2 and len(rescue_peaks) > 0:
        # اگر چند peak داریم، weighted median بگیر
        values = [x[1] for x in rescue_peaks]
        weights = [max(x[2], 0.2) for x in rescue_peaks]
        return weighted_median(values, weights), "peak_rescue_low_fft_failure"

    # ========================================================
    # Rule E: اگر POS/CHROM Peak باهم نزدیک‌اند، میانگین بگیر
    # ========================================================

    if pos_peak is not None and chrom_peak is not None:
        if 60 <= pos_peak <= 105 and 60 <= chrom_peak <= 105:
            if abs(pos_peak - chrom_peak) <= 10:
                return (pos_peak + chrom_peak) / 2.0, "pos_chrom_peak_agree"

    # ========================================================
    # Rule F: اگر یک peak منطقی بین 60 تا 100 داریم و FFTها پایین‌اند
    # ========================================================

    good_peaks = []

    for name, hr, conf in candidates:
        if "peak" in name and 60 <= hr <= 100:
            good_peaks.append((name, hr, conf))

    if len(good_peaks) > 0:
        best = max(good_peaks, key=lambda x: x[2])
        return best[1], f"{best[0]}_best_peak"

    # ========================================================
    # Rule G: weighted median از کاندیدهای فیزیولوژیک
    # ========================================================

    physiological = []

    for name, hr, conf in candidates:
        if 50 <= hr <= 110:
            physiological.append((name, hr, max(conf, 0.2)))

    if len(physiological) > 0:
        values = [x[1] for x in physiological]
        weights = [x[2] for x in physiological]
        return weighted_median(values, weights), "weighted_median_physiological"

    # Final fallback
    best = max(candidates, key=lambda x: x[2])
    return best[1], f"fallback_{best[0]}"


# =========================
# Video processing
# =========================

cap = cv2.VideoCapture(VIDEO_PATH)

if not cap.isOpened():
    raise RuntimeError("Video could not be opened.")

video_fps = cap.get(cv2.CAP_PROP_FPS)

if video_fps <= 0:
    video_fps = 30.0

print("Video FPS:", video_fps)

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

times = []
rgb_values = []
green_values = []
preview_frames = []

frame_idx = 0

while True:
    ret, frame = cap.read()

    if not ret:
        break

    time_sec = frame_idx / video_fps
    frame_idx += 1

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=3,
        minSize=(100, 100)
    )

    if len(faces) == 0:
        continue

    face = sorted(faces, key=lambda f: f[2] * f[3], reverse=True)[0]
    rois = get_rois(face, frame.shape)

    roi_rgbs = []

    for roi in rois.values():
        value = mean_rgb_from_roi(frame, roi)

        if value is not None:
            roi_rgbs.append(value)

    if len(roi_rgbs) == 0:
        continue

    mean_rgb = np.mean(np.asarray(roi_rgbs), axis=0)

    times.append(time_sec)
    rgb_values.append(mean_rgb)
    green_values.append(mean_rgb[1])

    if len(preview_frames) < 5:
        vis = frame.copy()
        x, y, w, h = face

        cv2.rectangle(
            vis,
            (x, y),
            (x + w, y + h),
            (0, 255, 0),
            2
        )

        colors = {
            "forehead": (0, 0, 255),
            "left_cheek": (255, 0, 0),
            "right_cheek": (255, 0, 0)
        }

        for name, roi in rois.items():
            rx, ry, rw, rh = roi

            cv2.rectangle(
                vis,
                (rx, ry),
                (rx + rw, ry + rh),
                colors[name],
                2
            )

            cv2.putText(
                vis,
                name,
                (rx, max(20, ry - 5)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                colors[name],
                1
            )

        preview_frames.append(vis)

cap.release()

times = np.asarray(times)
rgb_values = np.asarray(rgb_values)
green_values = np.asarray(green_values)

print("Extracted samples:", len(times))

if len(times) < 80:
    raise RuntimeError("Not enough valid face samples.")

print("Preview frames:")
print("Green rectangle = face")
print("Red rectangle = forehead")
print("Blue rectangles = cheeks")

for frame in preview_frames:
    cv2_imshow(frame)

fs = (len(times) - 1) / (times[-1] - times[0])

print("Estimated sampling rate:", fs)

# =========================
# Build rPPG signals
# =========================

green_raw = remove_spikes(green_values)
green_norm = normalize_signal(green_raw)
green_filt = bandpass_filter(green_norm, fs, MIN_BPM, MAX_BPM)

pos_raw = pos_rppg(rgb_values, fs)
pos_raw = detrend(remove_spikes(pos_raw))
pos_norm = normalize_signal(pos_raw)
pos_filt = bandpass_filter(pos_norm, fs, MIN_BPM, MAX_BPM)

chrom_raw = chrom_rppg(rgb_values, fs)
chrom_raw = detrend(remove_spikes(chrom_raw))
chrom_norm = normalize_signal(chrom_raw)
chrom_filt = bandpass_filter(chrom_norm, fs, MIN_BPM, MAX_BPM)

signals = {
    "green": green_filt,
    "pos": pos_filt,
    "chrom": chrom_filt
}

# =========================
# HR estimation
# =========================

results = {}

for name, signal in signals.items():
    fft_hr, fft_conf = estimate_hr_fft(signal, fs)
    peak_hr, peak_conf = estimate_hr_peak(signal, fs)

    results[name] = {
        "fft_hr": fft_hr,
        "fft_conf": fft_conf,
        "peak_hr": peak_hr,
        "peak_conf": peak_conf
    }

final_hr, final_method = smart_select_hr(results)

# =========================
# Print results
# =========================

print("\n========== GLOBAL RESULTS ==========")

for name in results:
    print(f"\n--- {name.upper()} ---")

    fft_hr = results[name]["fft_hr"]
    peak_hr = results[name]["peak_hr"]

    print(
        "FFT HR:",
        "N/A" if fft_hr is None else f"{fft_hr:.2f} bpm",
        "| conf:",
        f"{results[name]['fft_conf']:.2f}"
    )

    print(
        "Peak HR:",
        "N/A" if peak_hr is None else f"{peak_hr:.2f} bpm",
        "| conf:",
        f"{results[name]['peak_conf']:.2f}"
    )

print("\n========== FINAL RESULT ==========")

print(
    "Final HR:",
    "N/A" if final_hr is None else f"{final_hr:.2f} bpm"
)

print("Final method:", final_method)

if GROUND_TRUTH_HR is not None and final_hr is not None:
    print("Sensor HR:", GROUND_TRUTH_HR)
    print("Absolute Error:", abs(final_hr - GROUND_TRUTH_HR))

# =========================
# Plots
# =========================

relative_time = times - times[0]

plt.figure(figsize=(14, 5))
plt.plot(relative_time, green_filt, label="Green filtered")
plt.plot(relative_time, pos_filt, label="POS filtered")
plt.plot(relative_time, chrom_filt, label="CHROM filtered")
plt.title(
    f"Filtered rPPG Signals | Final HR={final_hr:.2f} bpm"
    if final_hr is not None else
    "Filtered rPPG Signals"
)
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.grid(True)
plt.legend()
plt.show()


def compute_spectrum(signal, fs):
    x = signal - np.mean(signal)
    x = x * np.hanning(len(x))

    freqs = np.fft.rfftfreq(len(x), d=1.0 / fs)
    spec = np.abs(np.fft.rfft(x))
    bpm = freqs * 60.0

    return bpm, spec


plt.figure(figsize=(14, 5))

for name, signal in signals.items():
    bpm_axis, spec = compute_spectrum(signal, fs)
    mask = (bpm_axis >= MIN_BPM) & (bpm_axis <= MAX_BPM)

    plt.plot(
        bpm_axis[mask],
        spec[mask],
        label=f"{name.upper()} spectrum"
    )

if final_hr is not None:
    plt.axvline(
        final_hr,
        linestyle="--",
        label=f"Final HR={final_hr:.2f}"
    )

plt.title("FFT Spectrum Comparison")
plt.xlabel("Heart Rate (BPM)")
plt.ylabel("FFT Magnitude")
plt.grid(True)
plt.legend()
plt.show()

pos_peaks, _ = find_peaks(
    pos_filt - np.mean(pos_filt),
    distance=max(1, int(fs * 60 / MAX_BPM)),
    prominence=max(0.30 * np.std(pos_filt), 0.10)
)

plt.figure(figsize=(14, 5))
plt.plot(relative_time, pos_filt, label="POS filtered")
plt.plot(
    relative_time[pos_peaks],
    pos_filt[pos_peaks],
    "x",
    label="Detected POS peaks"
)
plt.title("Peak Detection on POS rPPG Signal")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.grid(True)
plt.legend()
plt.show()